/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscussionsIndexRouteImport } from './routes/discussions/index'
import { Route as DiscussionsDiscussionIdRouteImport } from './routes/discussions/$discussionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsIndexRoute = DiscussionsIndexRouteImport.update({
  id: '/discussions/',
  path: '/discussions/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsDiscussionIdRoute = DiscussionsDiscussionIdRouteImport.update({
  id: '/discussions/$discussionId',
  path: '/discussions/$discussionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discussions/$discussionId': typeof DiscussionsDiscussionIdRoute
  '/discussions': typeof DiscussionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discussions/$discussionId': typeof DiscussionsDiscussionIdRoute
  '/discussions': typeof DiscussionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discussions/$discussionId': typeof DiscussionsDiscussionIdRoute
  '/discussions/': typeof DiscussionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/discussions/$discussionId' | '/discussions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/discussions/$discussionId' | '/discussions'
  id: '__root__' | '/' | '/discussions/$discussionId' | '/discussions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscussionsDiscussionIdRoute: typeof DiscussionsDiscussionIdRoute
  DiscussionsIndexRoute: typeof DiscussionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions/': {
      id: '/discussions/'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof DiscussionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions/$discussionId': {
      id: '/discussions/$discussionId'
      path: '/discussions/$discussionId'
      fullPath: '/discussions/$discussionId'
      preLoaderRoute: typeof DiscussionsDiscussionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscussionsDiscussionIdRoute: DiscussionsDiscussionIdRoute,
  DiscussionsIndexRoute: DiscussionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
